FROM python:3.12-slim-bookworm

RUN apt-get update \
    && apt-get install --yes --no-install-recommends ca-certificates expect procps util-linux \
    && rm -rf /var/lib/apt/lists/*

COPY . /src
RUN python -m pip install --no-cache-dir /src

RUN mkdir -p /workspace && chmod 0777 /workspace
WORKDIR /workspace
CMD ["bash"]
