"""Managed Claude Code subagents for exact OpenRouter favorites."""

from __future__ import annotations

import hashlib
import json
import re
import shlex
import sys
from pathlib import Path
from typing import Any

from .models import namespaced_model
from .paths import agent_manifest_path, claude_agents_dir
from .storage import atomic_write_json, atomic_write_text, read_json_object

MANIFEST_VERSION = 1
MANAGED_MARKER = "<!-- Managed by claude-openrouter; regenerated by setup/select. -->"
HOOK_COMMAND_SUFFIX = "-m claude_openrouter _agent-hook"


def agent_name(model_id: str) -> str:
    """Return a readable, collision-resistant Claude subagent name."""
    slug = re.sub(r"[^a-z0-9]+", "-", model_id.casefold()).strip("-")
    slug = slug[:48].rstrip("-") or "model"
    digest = hashlib.sha256(model_id.encode()).hexdigest()[:8]
    return f"clor-{slug}-{digest}"


def _agent_document(model: dict[str, Any], name: str) -> str:
    model_id = str(model["id"])
    label = str(model.get("name") or model_id)
    description = (
        f"Run a delegated task with the exact OpenRouter favorite {label} ({model_id}). "
        "Choose this subagent when that model is requested. Do not pass the Agent model "
        "parameter; this definition owns the exact model route."
    )
    return f"""---
name: {json.dumps(name)}
description: {json.dumps(description)}
model: {json.dumps(namespaced_model(model_id))}
---

{MANAGED_MARKER}

Complete the delegated task using this configured OpenRouter model. Be explicit about
limitations and do not claim to be a native Anthropic model.
"""


def hook_command() -> str:
    executable = shlex.quote(str(Path(sys.executable).resolve()))
    return f"{executable} {HOOK_COMMAND_SUFFIX}"


def managed_hook_group() -> dict[str, Any]:
    return {
        "matcher": "Agent",
        "hooks": [{"type": "command", "command": hook_command()}],
    }


def is_managed_hook_group(value: Any) -> bool:
    if not isinstance(value, dict) or value.get("matcher") != "Agent":
        return False
    hooks = value.get("hooks")
    return isinstance(hooks, list) and any(
        isinstance(hook, dict)
        and isinstance(hook.get("command"), str)
        and hook["command"].endswith(HOOK_COMMAND_SUFFIX)
        for hook in hooks
    )


def _safe_managed_path(filename: str) -> Path | None:
    if Path(filename).name != filename:
        return None
    path = claude_agents_dir() / filename
    if path.resolve().parent != claude_agents_dir().resolve():
        return None
    return path


def _remove_manifest_files(manifest: dict[str, Any]) -> None:
    agents = manifest.get("agents")
    if not isinstance(agents, dict):
        return
    for entry in agents.values():
        if not isinstance(entry, dict) or not isinstance(entry.get("file"), str):
            continue
        path = _safe_managed_path(entry["file"])
        if path is None or not path.exists():
            continue
        try:
            managed = MANAGED_MARKER in path.read_text(encoding="utf-8")
        except OSError:
            managed = False
        if managed:
            path.unlink()


def sync_managed_agents(models: list[dict[str, Any]]) -> dict[str, str]:
    """Replace clor-owned subagent definitions and return name-to-model routes."""
    manifest_path = agent_manifest_path()
    old_manifest = read_json_object(manifest_path, missing_ok=True)
    _remove_manifest_files(old_manifest)

    entries: dict[str, dict[str, str]] = {}
    routes: dict[str, str] = {}
    for model in models:
        model_id = str(model["id"])
        name = agent_name(model_id)
        filename = f"{name}.md"
        path = _safe_managed_path(filename)
        assert path is not None
        if path.exists() and MANAGED_MARKER not in path.read_text(encoding="utf-8"):
            raise RuntimeError(f"refusing to replace non-clor Claude subagent: {path}")
        atomic_write_text(path, _agent_document(model, name), 0o600)
        route = namespaced_model(model_id)
        entries[name] = {"file": filename, "model": route}
        routes[name] = route

    atomic_write_json(
        manifest_path,
        {"version": MANIFEST_VERSION, "agents": entries},
    )
    return routes


def remove_managed_agents() -> None:
    manifest_path = agent_manifest_path()
    manifest = read_json_object(manifest_path, missing_ok=True)
    _remove_manifest_files(manifest)
    manifest_path.unlink(missing_ok=True)
    directory = claude_agents_dir()
    if directory.exists() and not any(directory.iterdir()):
        directory.rmdir()


def rewrite_agent_input(event: Any) -> dict[str, Any] | None:
    """Pin a clor custom subagent to its definition instead of a native alias."""
    if not isinstance(event, dict) or event.get("tool_name") != "Agent":
        return None
    tool_input = event.get("tool_input")
    if not isinstance(tool_input, dict):
        return None
    subagent_type = tool_input.get("subagent_type")
    if not isinstance(subagent_type, str):
        return None
    manifest = read_json_object(agent_manifest_path(), missing_ok=True)
    agents = manifest.get("agents")
    if not isinstance(agents, dict) or subagent_type not in agents:
        return None
    updated = dict(tool_input)
    updated.pop("model", None)
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "permissionDecisionReason": (
                "Using the exact OpenRouter model selected by this clor subagent."
            ),
            "updatedInput": updated,
        }
    }


def run_agent_hook() -> int:
    """Best-effort Claude Code hook entry point; never disrupt unrelated tools."""
    try:
        event = json.load(sys.stdin)
        result = rewrite_agent_input(event)
        if result is not None:
            print(json.dumps(result, separators=(",", ":")))
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError):
        return 0
    return 0
